module.exports= [

  // "tuần vừa rồi",
  
  // "vào cuối tuần",
  // "vào trung tuần tháng 8",
  // "tuần đầu của Tết nguyên đán",
  // "ngày cuối tuần đầu tiên của mùa hè",

  // "thứ năm hằng tuần",


  "những năm đầu của {{theky}} {{centuryxx}}",
  "{{theky}} {{centuryxx}}",
  // "{{theky}} {{centuryxx}} trước công nguyên",

  // "năm {{yearxx}} tcn",
  "năm {{year}} tcn",
  "thập niên {{year}}",

  "giữa {{theky}} {{centuryxx}}",
  "đầu {{theky}} {{centuryxx}}",
  "cuối {{theky}} {{centuryxx}}",
  "vào {{theky}} {{centuryxx}}",
  "những năm của {{theky}} {{centuryxx}}",
  

  "sau {{numberic}} {{tuanngay}}",
  "sau đó {{numberic}} {{tuanngay}}",
  "sau {{numberic}} {{tuanngay}} nữa",
  "{{numberic}} {{tuanngay}} tới",
  "{{numberic}} {{tuanngay}} sau",
  
  "sau {{it}} {{tuanngay}}",
  "{{it}} {{tuanngay}} nữa",

  "cuối {{tuanngay}} trước",
  "đầu {{tuanngay}} trước",
  "{{tuanngay}} trước",
  "{{tuanngay}} qua",

  "{{sangNext}} {{namtgngay}}",
  "{{sangNext}} {{namtgngay}} tới",
  "{{sangNext}} {{namtgngay}} sau",
  "{{sangNext}} {{tuanngay}}",
  "{{sangNext}} {{tuanngay}} tới",
  "{{sangNext}} {{tuanngay}} sau",

  "cách đây {{it}} {{namtgngay}}",
  "cách đây đã gần {{it}} {{namtgngay}}",
  "cách đây đã {{it}} {{namtgngay}}",
  "{{it}} {{namtgngay}} sau",
  "{{it}} {{namtgngay}} tới",

  "cuối {{namtgngay}} trước",
  "{{namtgngay}} trước",
  "{{namtgngay}} qua",

  "cuối {{namtgngay}} này",
  "đầu {{namtgngay}} này",
  "{{namtgngay}} này",

  "cuối {{namtgngay}} tới",
  "đầu {{namtgngay}} sau",
  "{{namtgngay}} sau",
  "{{namtgngay}} tiếp theo",
  "{{namtgngay}} tới",
  "{{namtgngay}} sau đó",

  "ngày {{maimot}} {{day}} tháng {{mon}}",

  
  "sau {{mothai}} {{namtgngay}}",
  "{{mothai}} {{namtgngay}} sau",
  "cách đây chừng {{mothai}} {{namtgngay}}",
  "hơn {{mothai}} {{namtgngay}} sau",
  "cách đây gần {{mothai}} {{namtgngay}}",
  "cách nay gần {{mothai}} {{namtgngay}}",
  "cách đây hàng {{mothai}} {{namtgngay}}",
  "cách đây {{mothai}} {{namtgngay}}",
  "cách nay {{mothai}} {{namtgngay}}",
  "cách đây khoảng {{mothai}} {{namtgngay}}",
  "cách đây hơn {{mothai}} {{namtgngay}}",
  "cách đây chưa đầy {{mothai}} {{namtgngay}}",
  "cách đây cả {{mothai}} {{namtgngay}}",

  "{{numberic}} {{namtgngay}} tới",
  "hơn {{numberic}} {{namtgngay}} sau",
  "cách đây gần {{numberic}} {{namtgngay}}",
  "tới {{numberic}} {{namtgngay}} sau",
  "cách đây đã {{numberic}} {{namtgngay}}",
  "{{numberic}} {{namtgngay}} đã qua",
  "cách nay gần {{numberic}} {{namtgngay}}",
  "{{numberic}} {{namtgngay}} sau",
  "{{numberic}} {{namtgngay}} đã qua",
  "cách nay {{numberic}} {{namtgngay}}",
  "cách đây {{numberic}} {{namtgngay}}",
  "sau {{numberic}} {{namtgngay}}",
  "gần {{numberic}} {{namtgngay}} nay",
  "hơn {{numberic}} {{namtgngay}} qua",
  "{{numberic}} {{namtgngay}} nay",
  "hơn {{numberic}} {{namtgngay}} trước",
  "trong {{numberic}} {{namtgngay}} qua",
  "từ hơn {{numberic}} {{namtgngay}} nay",
  "từ {{numberic}} {{namtgngay}} trước",
  "hơn {{numberic}} {{namtgngay}} nay",
  "khoảng {{numberic}} {{namtgngay}} qua",
  "đã {{numberic}} {{namtgngay}} nay",

  "suốt {{numberic}} {{namtgngay}} qua",
  "đã hơn {{numberic}} {{namtgngay}} nay",
  "từ {{numberic}} {{namtgngay}} nay",
  "khoảng {{numberic}} {{namtgngay}} nữa",
  "từ {{numberic}} {{namtgngay}} qua",
  "đã gần {{numberic}} {{namtgngay}} nay",
  "gần như {{numberic}} {{namtgngay}} nay",
  "từ hơn {{numberic}} {{namtgngay}} qua",
  "{{numberic}} {{namtgngay}} trước",
  "gần {{numberic}} {{namtgngay}} qua",
  "trong vòng {{numberic}} {{namtgngay}} tới",
  "sau {{numberic}} {{namtgngay}} nay",
  "{{numberic}} {{namtgngay}} nữa",
  "khoảng {{numberic}} {{namtgngay}} nay",
  "chừng {{numberic}} {{namtgngay}} nữa",
  "khoảng {{numberic}} {{namtgngay}} trước",
  "gần {{numberic}} {{namtgngay}} trước",
  "trong {{numberic}} {{namtgngay}} tới",
  "khoảng gần {{numberic}} {{namtgngay}} nay",

  "tháng {{mon}}",
  "năm {{year}}",
  "đầu tháng {{mon}}",
  "ngày {{day}}-{{mon}}",
  "tháng {{mon}}-{{year}}",
  "những năm {{yearxx}}",
  "ngày {{day}}-{{mon}}-{{year}}",
  "giữa tháng {{mon}}",
  "{{day}}-{{mon}}-{{year}}",
  
  "đầu năm {{year}}",
  "giữa tháng {{mon}} này",
  "tháng {{day}}-{{year}}",
  "sau {{year}}",
  "ngày {{day}}/{{mon}}/{{year}}",
  "{{day}}/{{mon}}/{{year}}",
  "tháng {{mon}}/{{year}}",
  "tháng {{mon}} năm {{year}}",
  "ngày {{day}} tháng {{mon}}",
  "{{day}} tháng {{mon}}",
  "ngày {{day}}/ {{mon}}/ {{year}}",
  "cuối năm {{year}}",
  "giữa năm {{year}}",
  "cuối tháng {{mon}}",
  "cuối tháng {{mon}} này",
  "cuối tháng {{mon}}/{{year}}",
  "ngày {{day}}-{{mon}}",
  "đầu tháng {{mon}} này",
  "tháng {{mon}} {{nayngoaisau}}",
  "đầu tháng {{mon}}/{{year}}",
  "ngày {{day}}/{{mon}} {{nayngoaisau}}",
  "bắt đầu năm {{year}}",
  
  "cuối năm {{yearxx}}",
  "ngày {{day}} tháng {{mon}} năm {{year}}",
  "ngày {{day}} tháng {{mon}}/{{year}}",
  "chiều {{day}}/{{mon}}",
  "năm {{yearxx}}",
  "đầu năm {{yearxx}}",
  "đến {{day}}/{{mon}}",
  "từ ngày {{day}}",
  "vào năm {{yearxx}}",
  "đầu tháng {{mon}} {{nayngoaisau}}",
  "đêm {{day}}",
  "từ {{day}}/{{mon}}",
  "vào tối {{day}}/{{mon}}",
  "hôm {{day}}/{{mon}}",
  "tối {{day}}/{{mon}}",
  "vào {{day}}/{{mon}}",
  "khoảng {{day}}/{{mon}}",
  "buổi sáng {{day}}/{{mon}}",
  "đêm {{day}}/{{mon}}",
  "đông {{day}}/{{mon}}",
  "từ tối {{day}}/{{mon}}",
  "{{day}}/{{mon}}",
  "vào ngày {{day}}",
  "ngày {{day}}",
  "vào đêm {{day}}",
  "từ đêm {{day}}",
  "từ chiều {{day}}/{{mon}}",
  "tới {{day}}/{{mon}}",
  "vào đêm {{day}}/{{mon}}",
  "từ năm {{yearxx}}",
  "từ tháng {{day}}/{{mon}}",
  "đến tháng {{mon}}",
  "đến năm {{yearxx}}",
  "sau năm {{yearxx}}",
  "vào sáng {{day}}/{{mon}}",
  "đầu tháng {{day}}/{{mon}}",
  "vào cuối tháng {{day}}/{{mon}}",
  "vào ngày {{day}}/{{mon}}",
  "đến hết đêm {{day}}/{{mon}}",
  "tối {{maimot}}",
  "chiều {{maimot}}",
  "chiều tối {{maimot}}",
  "sáng {{maimot}}",
  "vào tháng {{mon}}",
  "trưa {{day}}/{{mon}}/{{year}}",
  "sáng {{day}}/{{mon}}/{{year}}",
  "vào ngày {{day}}/{{mon}} tới",
  "ngày {{day}}/{{mon}} tới",
  "tối {{day}}/{{mon}}/{{year}}",
  "mùa hè năm {{yearxx}}",
  "cuối tháng {{day}}/{{mon}} này",
  "đêm {{day}}/{{mon}} tới",
  "trưa {{day}}/{{mon}}",
  "sáng nay {{day}}/{{mon}}",
  "đêm {{day}}/{{mon}}/{{year}}",
  "đến tận chiều {{day}}/{{mon}}",
  "đến tận {{day}}/{{mon}}",
  "hôm {{day}}/{{mon}}",
  "cuối tháng {{day}}/{{mon}}",
  "sáng {{day}}/{{mon}}",
  "thời điểm {{day}}/{{mon}}",
  "đến hết ngày {{day}}/{{mon}}",
  "năm {{day}}/{{mon}}",
  "vào tối ngày {{day}}/{{mon}}",
  "cuối năm {{yearxx}}",

  "ngày {{day}} tháng {{truocsau}}",
  "vào tháng {{truocsau}}",
  "tháng {{truocsau}}",
  "đầu tháng {{truocsau}}",
  "cuối tháng {{truocsau}}",
  "trong tháng {{truocsau}}",
  

  "vào dịp {{day}}/{{mon}}",
  "vào {{day}}/{{mon}} tới",
  "vào ngày {{day}}/{{mon}}",
  "đến hết ngày {{day}}/{{mon}}/{{year}}",
  "sáng ngày {{day}}/{{mon}}/{{year}}",
  "từ ngày {{day}}/{{mon}}",
  "khoảng thời gian {{day}}/{{mon}}",
  "tới năm {{yearxx}}",
  "đến tháng {{day}}/{{mon}}",
  "khoảng năm {{yearxx}}",
  "sáng ngày {{day}}/{{mon}}",
  "vào {{day}}/{{mon}} {{nayngoaisau}}",
  "vào tháng {{mon}} {{nayngoaisau}}",
  "vào {{day}}/{{mon}}/{{year}}",
  "đến tháng {{mon}} {{nayngoaisau}}",
  "hôm {{day}}/{{mon}} tới",
  "trưa ngày {{day}}",
  "vào tối {{maimot}} {{day}}/{{mon}}",
  "trước năm {{yearxx}}",
  "tháng {{mon}} này",
  "mùa thu năm {{yearxx}}",
  "sau ngày {{day}}/{{mon}}",
  "đến {{day}}/{{mon}} tới",
  "mùa xuân năm {{yearxx}}",
  "vào chiều {{day}}/{{mon}}",
  "lúc trước {{day}}/{{mon}}",
  "vào ngày {{day}}/{{mon}}/{{year}}",
  "cuối tháng {{mon}} {{nayngoaisau}}",
  "khoảng ngày {{day}}/{{mon}}",
  "sau {{day}}/{{mon}}",
  
  "tối ngày {{day}}",
  "vào thời điểm {{day}}/{{mon}}",
  "mùa đông năm {{yearxx}}",
  "đến ngày {{day}}",
  "khoảng {{day}}/{{mon}} {{nayngoaisau}}",
  "đến mùng {{day}}/{{mon}}",
  "vào sáng {{day}}",
  "tháng {{mon}} tới",
  "từ {{day}}/{{mon}} {{nayngoaisau}}",
  "ngày {{day}}/{{mon}}",
  "ngày {{day}}/{{mon}} {{nayngoaisau}}",
  "trước {{day}}/{{mon}}",
  "từ lúc {{day}}/{{mon}}",
  "đến ngày {{day}}/{{mon}}",
  "cuối ngày {{day}}/{{mon}}",
  "tới tháng {{mon}}",
  "chiều ngày {{day}}/{{mon}}",
  "từ tháng {{mon}}",
  "từ hôm {{day}}/{{mon}}",
  "vào hôm {{day}}/{{mon}}",
  "giai đoạn {{day}}/{{mon}}",
  "từ ngày {{day}}/{{mon}}/{{year}}",
  "đến hết tháng {{mon}}",
  "vào {{day}}/{{mon}}/{{year}} tới",
  "đầu mùng {{day}}/{{mon}}",
  "đầu {{day}}/{{mon}}",
  "chừng năm {{yearxx}}",
  "giữa năm {{yearxx}}",
  "chừng {{day}}/{{mon}}",
  "sáng ngày {{day}}",
  "hè năm {{year}}",
  "đêm tới {{day}}/{{mon}}",
  "từ năm {{day}}/{{mon}}",
  "khoảng tháng {{mon}} {{nayngoaisau}}",
  "lúc {{day}}/{{mon}}",
  "năm {{yearxx}} trước đây",
  "đến {{day}}/{{mon}}/{{year}}"
]